version: '3.7'

services:
  web:
    image: metas:2021.1
    container_name: django_server
    build:
      context: .
      dockerfile: django.Dockerfile
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db_server
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

#volumes:
#  postgres_data: